apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: myregistry.com/frontend:v2
        name: frontend
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: api-url
              key: url
            
      imagePullSecrets: 
      - name: regcred
